# version: '3.8'

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - "3100:3000"
#     command:
#       - npm run local
#     volumes:
#       - ./:/app/